// Code generated by mkduff.go; DO NOT EDIT.
// Run go generate from src/runtime to update.
// See mkduff.go for comments.

#include "textflag.h"

TEXT runtime·duffzero(SB), NOSPLIT|NOFRAME, $0-0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	MOV	ZERO, (A0)
	ADD	$8, A0
	RET

TEXT runtime·duffcopy(SB), NOSPLIT|NOFRAME, $0-0
	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	MOV	(A0), A2
	ADD	$8, A0
	MOV	A2, (A1)
	ADD	$8, A1

	RET
