// DO NOT EDIT THIS FILE. GENERATED BY xgen.

package cmt

import (
	"embedded/mmio"
	"unsafe"
)

type Periph struct {
	ICIALLU  RICIALLU
	_        uint32
	ICIMVAU  RICIMVAU
	DCIMVAC  RDCIMVAC
	DCISW    RDCISW
	DCCMVAU  RDCCMVAU
	DCCMVAC  RDCCMVAC
	DCCSW    RDCCSW
	DCCIMVAC RDCCIMVAC
	DCCISW   RDCCISW
}

func (p *Periph) BaseAddr() uintptr {
	return uintptr(unsafe.Pointer(p))
}

func CMT() *Periph { return (*Periph)(unsafe.Pointer(uintptr(0xE000EF50))) }

type ICIALLU uint32

type RICIALLU struct{ mmio.U32 }

func (r *RICIALLU) Bits(mask ICIALLU) ICIALLU { return ICIALLU(r.U32.Bits(uint32(mask))) }
func (r *RICIALLU) StoreBits(mask, b ICIALLU) { r.U32.StoreBits(uint32(mask), uint32(b)) }
func (r *RICIALLU) SetBits(mask ICIALLU)      { r.U32.SetBits(uint32(mask)) }
func (r *RICIALLU) ClearBits(mask ICIALLU)    { r.U32.ClearBits(uint32(mask)) }
func (r *RICIALLU) Load() ICIALLU             { return ICIALLU(r.U32.Load()) }
func (r *RICIALLU) Store(b ICIALLU)           { r.U32.Store(uint32(b)) }

type RMICIALLU struct{ mmio.UM32 }

func (rm RMICIALLU) Load() ICIALLU   { return ICIALLU(rm.UM32.Load()) }
func (rm RMICIALLU) Store(b ICIALLU) { rm.UM32.Store(uint32(b)) }

type ICIMVAU uint32

type RICIMVAU struct{ mmio.U32 }

func (r *RICIMVAU) Bits(mask ICIMVAU) ICIMVAU { return ICIMVAU(r.U32.Bits(uint32(mask))) }
func (r *RICIMVAU) StoreBits(mask, b ICIMVAU) { r.U32.StoreBits(uint32(mask), uint32(b)) }
func (r *RICIMVAU) SetBits(mask ICIMVAU)      { r.U32.SetBits(uint32(mask)) }
func (r *RICIMVAU) ClearBits(mask ICIMVAU)    { r.U32.ClearBits(uint32(mask)) }
func (r *RICIMVAU) Load() ICIMVAU             { return ICIMVAU(r.U32.Load()) }
func (r *RICIMVAU) Store(b ICIMVAU)           { r.U32.Store(uint32(b)) }

type RMICIMVAU struct{ mmio.UM32 }

func (rm RMICIMVAU) Load() ICIMVAU   { return ICIMVAU(rm.UM32.Load()) }
func (rm RMICIMVAU) Store(b ICIMVAU) { rm.UM32.Store(uint32(b)) }

type DCIMVAC uint32

type RDCIMVAC struct{ mmio.U32 }

func (r *RDCIMVAC) Bits(mask DCIMVAC) DCIMVAC { return DCIMVAC(r.U32.Bits(uint32(mask))) }
func (r *RDCIMVAC) StoreBits(mask, b DCIMVAC) { r.U32.StoreBits(uint32(mask), uint32(b)) }
func (r *RDCIMVAC) SetBits(mask DCIMVAC)      { r.U32.SetBits(uint32(mask)) }
func (r *RDCIMVAC) ClearBits(mask DCIMVAC)    { r.U32.ClearBits(uint32(mask)) }
func (r *RDCIMVAC) Load() DCIMVAC             { return DCIMVAC(r.U32.Load()) }
func (r *RDCIMVAC) Store(b DCIMVAC)           { r.U32.Store(uint32(b)) }

type RMDCIMVAC struct{ mmio.UM32 }

func (rm RMDCIMVAC) Load() DCIMVAC   { return DCIMVAC(rm.UM32.Load()) }
func (rm RMDCIMVAC) Store(b DCIMVAC) { rm.UM32.Store(uint32(b)) }

type DCISW uint32

type RDCISW struct{ mmio.U32 }

func (r *RDCISW) Bits(mask DCISW) DCISW   { return DCISW(r.U32.Bits(uint32(mask))) }
func (r *RDCISW) StoreBits(mask, b DCISW) { r.U32.StoreBits(uint32(mask), uint32(b)) }
func (r *RDCISW) SetBits(mask DCISW)      { r.U32.SetBits(uint32(mask)) }
func (r *RDCISW) ClearBits(mask DCISW)    { r.U32.ClearBits(uint32(mask)) }
func (r *RDCISW) Load() DCISW             { return DCISW(r.U32.Load()) }
func (r *RDCISW) Store(b DCISW)           { r.U32.Store(uint32(b)) }

type RMDCISW struct{ mmio.UM32 }

func (rm RMDCISW) Load() DCISW   { return DCISW(rm.UM32.Load()) }
func (rm RMDCISW) Store(b DCISW) { rm.UM32.Store(uint32(b)) }

type DCCMVAU uint32

type RDCCMVAU struct{ mmio.U32 }

func (r *RDCCMVAU) Bits(mask DCCMVAU) DCCMVAU { return DCCMVAU(r.U32.Bits(uint32(mask))) }
func (r *RDCCMVAU) StoreBits(mask, b DCCMVAU) { r.U32.StoreBits(uint32(mask), uint32(b)) }
func (r *RDCCMVAU) SetBits(mask DCCMVAU)      { r.U32.SetBits(uint32(mask)) }
func (r *RDCCMVAU) ClearBits(mask DCCMVAU)    { r.U32.ClearBits(uint32(mask)) }
func (r *RDCCMVAU) Load() DCCMVAU             { return DCCMVAU(r.U32.Load()) }
func (r *RDCCMVAU) Store(b DCCMVAU)           { r.U32.Store(uint32(b)) }

type RMDCCMVAU struct{ mmio.UM32 }

func (rm RMDCCMVAU) Load() DCCMVAU   { return DCCMVAU(rm.UM32.Load()) }
func (rm RMDCCMVAU) Store(b DCCMVAU) { rm.UM32.Store(uint32(b)) }

type DCCMVAC uint32

type RDCCMVAC struct{ mmio.U32 }

func (r *RDCCMVAC) Bits(mask DCCMVAC) DCCMVAC { return DCCMVAC(r.U32.Bits(uint32(mask))) }
func (r *RDCCMVAC) StoreBits(mask, b DCCMVAC) { r.U32.StoreBits(uint32(mask), uint32(b)) }
func (r *RDCCMVAC) SetBits(mask DCCMVAC)      { r.U32.SetBits(uint32(mask)) }
func (r *RDCCMVAC) ClearBits(mask DCCMVAC)    { r.U32.ClearBits(uint32(mask)) }
func (r *RDCCMVAC) Load() DCCMVAC             { return DCCMVAC(r.U32.Load()) }
func (r *RDCCMVAC) Store(b DCCMVAC)           { r.U32.Store(uint32(b)) }

type RMDCCMVAC struct{ mmio.UM32 }

func (rm RMDCCMVAC) Load() DCCMVAC   { return DCCMVAC(rm.UM32.Load()) }
func (rm RMDCCMVAC) Store(b DCCMVAC) { rm.UM32.Store(uint32(b)) }

type DCCSW uint32

type RDCCSW struct{ mmio.U32 }

func (r *RDCCSW) Bits(mask DCCSW) DCCSW   { return DCCSW(r.U32.Bits(uint32(mask))) }
func (r *RDCCSW) StoreBits(mask, b DCCSW) { r.U32.StoreBits(uint32(mask), uint32(b)) }
func (r *RDCCSW) SetBits(mask DCCSW)      { r.U32.SetBits(uint32(mask)) }
func (r *RDCCSW) ClearBits(mask DCCSW)    { r.U32.ClearBits(uint32(mask)) }
func (r *RDCCSW) Load() DCCSW             { return DCCSW(r.U32.Load()) }
func (r *RDCCSW) Store(b DCCSW)           { r.U32.Store(uint32(b)) }

type RMDCCSW struct{ mmio.UM32 }

func (rm RMDCCSW) Load() DCCSW   { return DCCSW(rm.UM32.Load()) }
func (rm RMDCCSW) Store(b DCCSW) { rm.UM32.Store(uint32(b)) }

type DCCIMVAC uint32

type RDCCIMVAC struct{ mmio.U32 }

func (r *RDCCIMVAC) Bits(mask DCCIMVAC) DCCIMVAC { return DCCIMVAC(r.U32.Bits(uint32(mask))) }
func (r *RDCCIMVAC) StoreBits(mask, b DCCIMVAC)  { r.U32.StoreBits(uint32(mask), uint32(b)) }
func (r *RDCCIMVAC) SetBits(mask DCCIMVAC)       { r.U32.SetBits(uint32(mask)) }
func (r *RDCCIMVAC) ClearBits(mask DCCIMVAC)     { r.U32.ClearBits(uint32(mask)) }
func (r *RDCCIMVAC) Load() DCCIMVAC              { return DCCIMVAC(r.U32.Load()) }
func (r *RDCCIMVAC) Store(b DCCIMVAC)            { r.U32.Store(uint32(b)) }

type RMDCCIMVAC struct{ mmio.UM32 }

func (rm RMDCCIMVAC) Load() DCCIMVAC   { return DCCIMVAC(rm.UM32.Load()) }
func (rm RMDCCIMVAC) Store(b DCCIMVAC) { rm.UM32.Store(uint32(b)) }

type DCCISW uint32

type RDCCISW struct{ mmio.U32 }

func (r *RDCCISW) Bits(mask DCCISW) DCCISW  { return DCCISW(r.U32.Bits(uint32(mask))) }
func (r *RDCCISW) StoreBits(mask, b DCCISW) { r.U32.StoreBits(uint32(mask), uint32(b)) }
func (r *RDCCISW) SetBits(mask DCCISW)      { r.U32.SetBits(uint32(mask)) }
func (r *RDCCISW) ClearBits(mask DCCISW)    { r.U32.ClearBits(uint32(mask)) }
func (r *RDCCISW) Load() DCCISW             { return DCCISW(r.U32.Load()) }
func (r *RDCCISW) Store(b DCCISW)           { r.U32.Store(uint32(b)) }

type RMDCCISW struct{ mmio.UM32 }

func (rm RMDCCISW) Load() DCCISW   { return DCCISW(rm.UM32.Load()) }
func (rm RMDCCISW) Store(b DCCISW) { rm.UM32.Store(uint32(b)) }
