// Code generated by mksizeclasses.go; DO NOT EDIT.
//go:generate go -C ../../../runtime/_mkmalloc run mksizeclasses.go

//go:build noos && thumb

package gc

// class  bytes/obj  bytes/span  objects  tail waste  max waste  min align
//     1          8         512       64           0     87.50%          8
//     2         16         512       32           0     43.75%         16
//     3         24         512       21           8     30.27%          8
//     4         32         512       16           0     21.88%         32
//     5         48         512       10          32     35.55%         16
//     6         64         512        8           0     23.44%         64
//     7         80         512        6          32     23.83%         16
//     8         96         512        5          32     20.90%         32
//     9        128         512        4           0     24.22%        128
//    10        144        1024        7          16     11.82%         16
//    11        160         512        3          32     15.04%         32
//    12        176        1536        8         128     16.15%         16
//    13        192        1024        5          64     13.57%         64
//    14        208        1536        7          80     12.04%         16
//    15        256         512        2           0     18.36%        256
//    16        288        1536        5          96     16.34%         32
//    17        320        1024        3          64     15.33%         64
//    18        384        1536        4           0     16.41%        128
//    19        416        2560        6          64      9.77%         32
//    20        512         512        1           0     18.55%        512
//    21        640        2560        4           0     19.84%        128
//    22        640        2048        3         128      6.10%        128
//    23        768        1536        2           0     16.54%        256
//    24        832        2560        3          64      9.88%         64
//    25       1024        1024        1           0     18.65%        512
//    26       1280        2560        2           0     19.92%        256
//    27       1536        1536        1           0     16.60%        512
//    28       1792        3584        2           0     14.23%        256
//    29       2048        2048        1           0     12.45%        512

// alignment  bits  min obj size
//         8     3             8
//        16     4            32
//        32     5           256
//        64     6           512
//       256     8          1024
//       512     9          2048

const (
	MinHeapAlign       = 8
	MaxSmallSize       = 2048
	SmallSizeDiv       = 8
	SmallSizeMax       = 256
	LargeSizeDiv       = 128
	NumSizeClasses     = 30
	PageShift          = 9
	MaxObjsPerSpan     = 64
	MaxSizeClassNPages = 7
	TinySize           = 16
	TinySizeClass      = 2
)

var SizeClassToSize = [NumSizeClasses]uint16{0, 8, 16, 24, 32, 48, 64, 80, 96, 128, 144, 160, 176, 192, 208, 256, 288, 320, 384, 416, 512, 640, 640, 768, 832, 1024, 1280, 1536, 1792, 2048}
var SizeClassToNPages = [NumSizeClasses]uint8{0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 3, 2, 3, 1, 3, 2, 3, 5, 1, 5, 4, 3, 5, 2, 5, 3, 7, 4}
var SizeClassToDivMagic = [NumSizeClasses]uint32{0, ^uint32(0)/8 + 1, ^uint32(0)/16 + 1, ^uint32(0)/24 + 1, ^uint32(0)/32 + 1, ^uint32(0)/48 + 1, ^uint32(0)/64 + 1, ^uint32(0)/80 + 1, ^uint32(0)/96 + 1, ^uint32(0)/128 + 1, ^uint32(0)/144 + 1, ^uint32(0)/160 + 1, ^uint32(0)/176 + 1, ^uint32(0)/192 + 1, ^uint32(0)/208 + 1, ^uint32(0)/256 + 1, ^uint32(0)/288 + 1, ^uint32(0)/320 + 1, ^uint32(0)/384 + 1, ^uint32(0)/416 + 1, ^uint32(0)/512 + 1, ^uint32(0)/640 + 1, ^uint32(0)/640 + 1, ^uint32(0)/768 + 1, ^uint32(0)/832 + 1, ^uint32(0)/1024 + 1, ^uint32(0)/1280 + 1, ^uint32(0)/1536 + 1, ^uint32(0)/1792 + 1, ^uint32(0)/2048 + 1}
var SizeToSizeClass8 = [SmallSizeMax/SmallSizeDiv + 1]uint8{0, 1, 2, 3, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 9, 9, 10, 10, 11, 11, 12, 12, 13, 13, 14, 14, 15, 15, 15, 15, 15, 15}
var SizeToSizeClass128 = [(MaxSmallSize-SmallSizeMax)/LargeSizeDiv + 1]uint8{15, 18, 20, 21, 23, 25, 25, 26, 26, 27, 27, 28, 28, 29, 29}
