// Code generated by mksizeclasses_mcu.go; DO NOT EDIT.
//go:generate go run mksizeclasses_mcu.go

//go:build noos && thumb

package runtime

// class  bytes/obj  bytes/span  objects  tail waste  max waste  min align
//     1          8         512       64           0     87.50%          8
//     2         16         512       32           0     43.75%         16
//     3         24         512       21           8     30.27%          8
//     4         32         512       16           0     21.88%         32
//     5         48         512       10          32     35.55%         16
//     6         64         512        8           0     23.44%         64
//     7         80         512        6          32     23.83%         16
//     8         96         512        5          32     20.90%         32
//     9        128         512        4           0     24.22%        128
//    10        160         512        3          32     24.41%         32
//    11        192        1024        5          64     21.39%         64
//    12        256         512        2           0     24.61%        256
//    13        320        1024        3          64     24.71%         64
//    14        384        1536        4           0     16.41%        128
//    15        512         512        1           0     24.80%        512

// alignment  bits  min obj size
//         8     3             8
//        16     4            32
//        32     5            96
//        64     6           192
//       128     7           384
//       512     9           512

const (
	minHeapAlign    = 8
	_MaxSmallSize   = 512
	smallSizeDiv    = 8
	smallSizeMax    = 256
	largeSizeDiv    = 128
	_NumSizeClasses = 16
	_PageShift      = 9
	maxObjsPerSpan  = 64
)

var class_to_size = [_NumSizeClasses]uint16{0, 8, 16, 24, 32, 48, 64, 80, 96, 128, 160, 192, 256, 320, 384, 512}
var class_to_allocnpages = [_NumSizeClasses]uint8{0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 3, 1}
var class_to_divmagic = [_NumSizeClasses]uint32{0, ^uint32(0)/8 + 1, ^uint32(0)/16 + 1, ^uint32(0)/24 + 1, ^uint32(0)/32 + 1, ^uint32(0)/48 + 1, ^uint32(0)/64 + 1, ^uint32(0)/80 + 1, ^uint32(0)/96 + 1, ^uint32(0)/128 + 1, ^uint32(0)/160 + 1, ^uint32(0)/192 + 1, ^uint32(0)/256 + 1, ^uint32(0)/320 + 1, ^uint32(0)/384 + 1, ^uint32(0)/512 + 1}
var size_to_class8 = [smallSizeMax/smallSizeDiv + 1]uint8{0, 1, 2, 3, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 9, 9, 10, 10, 10, 10, 11, 11, 11, 11, 12, 12, 12, 12, 12, 12, 12, 12}
var size_to_class128 = [(_MaxSmallSize-smallSizeMax)/largeSizeDiv + 1]uint8{12, 14, 15}
