// DO NOT EDIT THIS FILE. GENERATED BY xgen.

package fpu

import (
	"embedded/mmio"
	"unsafe"
)

type Periph struct {
	CPACR  mmio.R32[CPACR]
	_      [106]uint32
	FPCCR  mmio.R32[FPCCR]
	FPCAR  mmio.R32[FPCAR]
	FPDSCR mmio.R32[FPDSCR]
}

func FPU() *Periph { return (*Periph)(unsafe.Pointer(uintptr(0xe000ED88))) }

func (p *Periph) BaseAddr() uintptr {
	return uintptr(unsafe.Pointer(p))
}

type CPACR uint32

func CP0_(p *Periph) mmio.RM32[CPACR]  { return mmio.RM32[CPACR]{&p.CPACR, CP0} }
func CP1_(p *Periph) mmio.RM32[CPACR]  { return mmio.RM32[CPACR]{&p.CPACR, CP1} }
func CP2_(p *Periph) mmio.RM32[CPACR]  { return mmio.RM32[CPACR]{&p.CPACR, CP2} }
func CP3_(p *Periph) mmio.RM32[CPACR]  { return mmio.RM32[CPACR]{&p.CPACR, CP3} }
func CP4_(p *Periph) mmio.RM32[CPACR]  { return mmio.RM32[CPACR]{&p.CPACR, CP4} }
func CP5_(p *Periph) mmio.RM32[CPACR]  { return mmio.RM32[CPACR]{&p.CPACR, CP5} }
func CP6_(p *Periph) mmio.RM32[CPACR]  { return mmio.RM32[CPACR]{&p.CPACR, CP6} }
func CP7_(p *Periph) mmio.RM32[CPACR]  { return mmio.RM32[CPACR]{&p.CPACR, CP7} }
func CP10_(p *Periph) mmio.RM32[CPACR] { return mmio.RM32[CPACR]{&p.CPACR, CP10} }
func CP11_(p *Periph) mmio.RM32[CPACR] { return mmio.RM32[CPACR]{&p.CPACR, CP11} }

type FPCCR uint32

func LSPACT_(p *Periph) mmio.RM32[FPCCR]    { return mmio.RM32[FPCCR]{&p.FPCCR, LSPACT} }
func USER_(p *Periph) mmio.RM32[FPCCR]      { return mmio.RM32[FPCCR]{&p.FPCCR, USER} }
func S_(p *Periph) mmio.RM32[FPCCR]         { return mmio.RM32[FPCCR]{&p.FPCCR, S} }
func THREAD_(p *Periph) mmio.RM32[FPCCR]    { return mmio.RM32[FPCCR]{&p.FPCCR, THREAD} }
func HFRDY_(p *Periph) mmio.RM32[FPCCR]     { return mmio.RM32[FPCCR]{&p.FPCCR, HFRDY} }
func MMRDY_(p *Periph) mmio.RM32[FPCCR]     { return mmio.RM32[FPCCR]{&p.FPCCR, MMRDY} }
func BFRDY_(p *Periph) mmio.RM32[FPCCR]     { return mmio.RM32[FPCCR]{&p.FPCCR, BFRDY} }
func MONRDY_(p *Periph) mmio.RM32[FPCCR]    { return mmio.RM32[FPCCR]{&p.FPCCR, MONRDY} }
func SPLIMVIOL_(p *Periph) mmio.RM32[FPCCR] { return mmio.RM32[FPCCR]{&p.FPCCR, SPLIMVIOL} }
func UFRDY_(p *Periph) mmio.RM32[FPCCR]     { return mmio.RM32[FPCCR]{&p.FPCCR, UFRDY} }
func TS_(p *Periph) mmio.RM32[FPCCR]        { return mmio.RM32[FPCCR]{&p.FPCCR, TS} }
func CLRONRETS_(p *Periph) mmio.RM32[FPCCR] { return mmio.RM32[FPCCR]{&p.FPCCR, CLRONRETS} }
func CLRONRET_(p *Periph) mmio.RM32[FPCCR]  { return mmio.RM32[FPCCR]{&p.FPCCR, CLRONRET} }
func LSPENS_(p *Periph) mmio.RM32[FPCCR]    { return mmio.RM32[FPCCR]{&p.FPCCR, LSPENS} }
func LSPEN_(p *Periph) mmio.RM32[FPCCR]     { return mmio.RM32[FPCCR]{&p.FPCCR, LSPEN} }
func ASPEN_(p *Periph) mmio.RM32[FPCCR]     { return mmio.RM32[FPCCR]{&p.FPCCR, ASPEN} }

type FPCAR uint32

func ADDRESS_(p *Periph) mmio.RM32[FPCAR] { return mmio.RM32[FPCAR]{&p.FPCAR, ADDRESS} }

type FPDSCR uint32

func RMode_(p *Periph) mmio.RM32[FPDSCR] { return mmio.RM32[FPDSCR]{&p.FPDSCR, RMode} }
func FZ_(p *Periph) mmio.RM32[FPDSCR]    { return mmio.RM32[FPDSCR]{&p.FPDSCR, FZ} }
func DN_(p *Periph) mmio.RM32[FPDSCR]    { return mmio.RM32[FPDSCR]{&p.FPDSCR, DN} }
func AHP_(p *Periph) mmio.RM32[FPDSCR]   { return mmio.RM32[FPDSCR]{&p.FPDSCR, AHP} }
