// DO NOT EDIT THIS FILE. GENERATED BY xgen.

package scb

import (
	"embedded/mmio"
	"unsafe"
)

type Periph struct {
	CPUID mmio.R32[CPUID]
	ICSR  mmio.R32[ICSR]
	VTOR  mmio.R32[VTOR]
	AIRCR mmio.R32[AIRCR]
	SCR   mmio.R32[SCR]
	CCR   mmio.R32[CCR]
	SHPR1 mmio.R32[SHPR1]
	SHPR2 mmio.R32[SHPR2]
	SHPR3 mmio.R32[SHPR3]
	SHCSR mmio.R32[SHCSR]
	CFSR  mmio.R32[CFSR]
	HFSR  mmio.R32[HFSR]
	_     uint32
	MMFR  mmio.R32[uint32]
	BFAR  mmio.R32[uint32]
	AFSR  mmio.R32[uint32]
}

func SCB() *Periph { return (*Periph)(unsafe.Pointer(uintptr(0xE000ED00))) }

func (p *Periph) BaseAddr() uintptr {
	return uintptr(unsafe.Pointer(p))
}

type CPUID uint32

func Revision_(p *Periph) mmio.RM32[CPUID]    { return mmio.RM32[CPUID]{&p.CPUID, Revision} }
func PartNo_(p *Periph) mmio.RM32[CPUID]      { return mmio.RM32[CPUID]{&p.CPUID, PartNo} }
func Constant_(p *Periph) mmio.RM32[CPUID]    { return mmio.RM32[CPUID]{&p.CPUID, Constant} }
func Variant_(p *Periph) mmio.RM32[CPUID]     { return mmio.RM32[CPUID]{&p.CPUID, Variant} }
func Implementer_(p *Periph) mmio.RM32[CPUID] { return mmio.RM32[CPUID]{&p.CPUID, Implementer} }

type ICSR uint32

func VECTACTIVE_(p *Periph) mmio.RM32[ICSR]  { return mmio.RM32[ICSR]{&p.ICSR, VECTACTIVE} }
func RETTOBASE_(p *Periph) mmio.RM32[ICSR]   { return mmio.RM32[ICSR]{&p.ICSR, RETTOBASE} }
func VECTPENDING_(p *Periph) mmio.RM32[ICSR] { return mmio.RM32[ICSR]{&p.ICSR, VECTPENDING} }
func ISRPENDING_(p *Periph) mmio.RM32[ICSR]  { return mmio.RM32[ICSR]{&p.ICSR, ISRPENDING} }
func PENDSTCLR_(p *Periph) mmio.RM32[ICSR]   { return mmio.RM32[ICSR]{&p.ICSR, PENDSTCLR} }
func PENDSTSET_(p *Periph) mmio.RM32[ICSR]   { return mmio.RM32[ICSR]{&p.ICSR, PENDSTSET} }
func PENDSVCLR_(p *Periph) mmio.RM32[ICSR]   { return mmio.RM32[ICSR]{&p.ICSR, PENDSVCLR} }
func PENDSVSET_(p *Periph) mmio.RM32[ICSR]   { return mmio.RM32[ICSR]{&p.ICSR, PENDSVSET} }
func NMIPENDSET_(p *Periph) mmio.RM32[ICSR]  { return mmio.RM32[ICSR]{&p.ICSR, NMIPENDSET} }

type VTOR uint32

func TBLOFF_(p *Periph) mmio.RM32[VTOR] { return mmio.RM32[VTOR]{&p.VTOR, TBLOFF} }

type AIRCR uint32

func VECTRESET_(p *Periph) mmio.RM32[AIRCR]     { return mmio.RM32[AIRCR]{&p.AIRCR, VECTRESET} }
func VECTCLRACTIVE_(p *Periph) mmio.RM32[AIRCR] { return mmio.RM32[AIRCR]{&p.AIRCR, VECTCLRACTIVE} }
func SYSRESETREQ_(p *Periph) mmio.RM32[AIRCR]   { return mmio.RM32[AIRCR]{&p.AIRCR, SYSRESETREQ} }
func PRIGROUP_(p *Periph) mmio.RM32[AIRCR]      { return mmio.RM32[AIRCR]{&p.AIRCR, PRIGROUP} }
func ENDIANNESS_(p *Periph) mmio.RM32[AIRCR]    { return mmio.RM32[AIRCR]{&p.AIRCR, ENDIANNESS} }
func VECTKEY_(p *Periph) mmio.RM32[AIRCR]       { return mmio.RM32[AIRCR]{&p.AIRCR, VECTKEY} }

type SCR uint32

func SLEEPONEXIT_(p *Periph) mmio.RM32[SCR] { return mmio.RM32[SCR]{&p.SCR, SLEEPONEXIT} }
func SLEEPDEEP_(p *Periph) mmio.RM32[SCR]   { return mmio.RM32[SCR]{&p.SCR, SLEEPDEEP} }
func SEVONPEND_(p *Periph) mmio.RM32[SCR]   { return mmio.RM32[SCR]{&p.SCR, SEVONPEND} }

type CCR uint32

func NONBASETHRDENA_(p *Periph) mmio.RM32[CCR] { return mmio.RM32[CCR]{&p.CCR, NONBASETHRDENA} }
func USERSETMPEND_(p *Periph) mmio.RM32[CCR]   { return mmio.RM32[CCR]{&p.CCR, USERSETMPEND} }
func UNALIGN_TRP_(p *Periph) mmio.RM32[CCR]    { return mmio.RM32[CCR]{&p.CCR, UNALIGN_TRP} }
func DIV_0_TRP_(p *Periph) mmio.RM32[CCR]      { return mmio.RM32[CCR]{&p.CCR, DIV_0_TRP} }
func BFHFNMIGN_(p *Periph) mmio.RM32[CCR]      { return mmio.RM32[CCR]{&p.CCR, BFHFNMIGN} }
func STKALIGN_(p *Periph) mmio.RM32[CCR]       { return mmio.RM32[CCR]{&p.CCR, STKALIGN} }
func DC_(p *Periph) mmio.RM32[CCR]             { return mmio.RM32[CCR]{&p.CCR, DC} }
func IC_(p *Periph) mmio.RM32[CCR]             { return mmio.RM32[CCR]{&p.CCR, IC} }
func BP_(p *Periph) mmio.RM32[CCR]             { return mmio.RM32[CCR]{&p.CCR, BP} }

type SHPR1 uint32

func PRI_MemManage_(p *Periph) mmio.RM32[SHPR1]  { return mmio.RM32[SHPR1]{&p.SHPR1, PRI_MemManage} }
func PRI_BusFault_(p *Periph) mmio.RM32[SHPR1]   { return mmio.RM32[SHPR1]{&p.SHPR1, PRI_BusFault} }
func PRI_UsageFault_(p *Periph) mmio.RM32[SHPR1] { return mmio.RM32[SHPR1]{&p.SHPR1, PRI_UsageFault} }

type SHPR2 uint32

func PRI_SVCall_(p *Periph) mmio.RM32[SHPR2] { return mmio.RM32[SHPR2]{&p.SHPR2, PRI_SVCall} }

type SHPR3 uint32

func PRI_PendSV_(p *Periph) mmio.RM32[SHPR3]  { return mmio.RM32[SHPR3]{&p.SHPR3, PRI_PendSV} }
func PRI_SysTick_(p *Periph) mmio.RM32[SHPR3] { return mmio.RM32[SHPR3]{&p.SHPR3, PRI_SysTick} }

type SHCSR uint32

func MEMFAULTACT_(p *Periph) mmio.RM32[SHCSR]    { return mmio.RM32[SHCSR]{&p.SHCSR, MEMFAULTACT} }
func BUSFAULTACT_(p *Periph) mmio.RM32[SHCSR]    { return mmio.RM32[SHCSR]{&p.SHCSR, BUSFAULTACT} }
func USGFAULTACT_(p *Periph) mmio.RM32[SHCSR]    { return mmio.RM32[SHCSR]{&p.SHCSR, USGFAULTACT} }
func SVCALLACT_(p *Periph) mmio.RM32[SHCSR]      { return mmio.RM32[SHCSR]{&p.SHCSR, SVCALLACT} }
func MONITORACT_(p *Periph) mmio.RM32[SHCSR]     { return mmio.RM32[SHCSR]{&p.SHCSR, MONITORACT} }
func PENDSVACT_(p *Periph) mmio.RM32[SHCSR]      { return mmio.RM32[SHCSR]{&p.SHCSR, PENDSVACT} }
func SYSTICKACT_(p *Periph) mmio.RM32[SHCSR]     { return mmio.RM32[SHCSR]{&p.SHCSR, SYSTICKACT} }
func USGFAULTPENDED_(p *Periph) mmio.RM32[SHCSR] { return mmio.RM32[SHCSR]{&p.SHCSR, USGFAULTPENDED} }
func MEMFAULTPENDED_(p *Periph) mmio.RM32[SHCSR] { return mmio.RM32[SHCSR]{&p.SHCSR, MEMFAULTPENDED} }
func BUSFAULTPENDED_(p *Periph) mmio.RM32[SHCSR] { return mmio.RM32[SHCSR]{&p.SHCSR, BUSFAULTPENDED} }
func SVCALLPENDED_(p *Periph) mmio.RM32[SHCSR]   { return mmio.RM32[SHCSR]{&p.SHCSR, SVCALLPENDED} }
func MEMFAULTENA_(p *Periph) mmio.RM32[SHCSR]    { return mmio.RM32[SHCSR]{&p.SHCSR, MEMFAULTENA} }
func BUSFAULTENA_(p *Periph) mmio.RM32[SHCSR]    { return mmio.RM32[SHCSR]{&p.SHCSR, BUSFAULTENA} }
func USGFAULTENA_(p *Periph) mmio.RM32[SHCSR]    { return mmio.RM32[SHCSR]{&p.SHCSR, USGFAULTENA} }

type CFSR uint32

func IACCVIOL_(p *Periph) mmio.RM32[CFSR]    { return mmio.RM32[CFSR]{&p.CFSR, IACCVIOL} }
func DACCVIOL_(p *Periph) mmio.RM32[CFSR]    { return mmio.RM32[CFSR]{&p.CFSR, DACCVIOL} }
func MUNSTKERR_(p *Periph) mmio.RM32[CFSR]   { return mmio.RM32[CFSR]{&p.CFSR, MUNSTKERR} }
func MSTKERR_(p *Periph) mmio.RM32[CFSR]     { return mmio.RM32[CFSR]{&p.CFSR, MSTKERR} }
func MLSPERR_(p *Periph) mmio.RM32[CFSR]     { return mmio.RM32[CFSR]{&p.CFSR, MLSPERR} }
func MMARVALID_(p *Periph) mmio.RM32[CFSR]   { return mmio.RM32[CFSR]{&p.CFSR, MMARVALID} }
func IBUSERR_(p *Periph) mmio.RM32[CFSR]     { return mmio.RM32[CFSR]{&p.CFSR, IBUSERR} }
func PRECISERR_(p *Periph) mmio.RM32[CFSR]   { return mmio.RM32[CFSR]{&p.CFSR, PRECISERR} }
func IMPRECISERR_(p *Periph) mmio.RM32[CFSR] { return mmio.RM32[CFSR]{&p.CFSR, IMPRECISERR} }
func UNSTKERR_(p *Periph) mmio.RM32[CFSR]    { return mmio.RM32[CFSR]{&p.CFSR, UNSTKERR} }
func STKERR_(p *Periph) mmio.RM32[CFSR]      { return mmio.RM32[CFSR]{&p.CFSR, STKERR} }
func LSPERR_(p *Periph) mmio.RM32[CFSR]      { return mmio.RM32[CFSR]{&p.CFSR, LSPERR} }
func BFARVALID_(p *Periph) mmio.RM32[CFSR]   { return mmio.RM32[CFSR]{&p.CFSR, BFARVALID} }
func UNDEFINSTR_(p *Periph) mmio.RM32[CFSR]  { return mmio.RM32[CFSR]{&p.CFSR, UNDEFINSTR} }
func INVSTATE_(p *Periph) mmio.RM32[CFSR]    { return mmio.RM32[CFSR]{&p.CFSR, INVSTATE} }
func INVPC_(p *Periph) mmio.RM32[CFSR]       { return mmio.RM32[CFSR]{&p.CFSR, INVPC} }
func NOCP_(p *Periph) mmio.RM32[CFSR]        { return mmio.RM32[CFSR]{&p.CFSR, NOCP} }
func UNALIGNED_(p *Periph) mmio.RM32[CFSR]   { return mmio.RM32[CFSR]{&p.CFSR, UNALIGNED} }
func DIVBYZERO_(p *Periph) mmio.RM32[CFSR]   { return mmio.RM32[CFSR]{&p.CFSR, DIVBYZERO} }

type HFSR uint32

func VECTTBL_(p *Periph) mmio.RM32[HFSR]  { return mmio.RM32[HFSR]{&p.HFSR, VECTTBL} }
func FORCED_(p *Periph) mmio.RM32[HFSR]   { return mmio.RM32[HFSR]{&p.HFSR, FORCED} }
func DEBUGEVT_(p *Periph) mmio.RM32[HFSR] { return mmio.RM32[HFSR]{&p.HFSR, DEBUGEVT} }
